### ISSUE TITLE
Add scss, php, all-js-min?

### ISSUE THREAD

**Issue by frankdema** [royandco/static-starter#59]
Hello, a great project. Great new demo site.

################################################

- is it possible to include scss?

e.g.
src/assets/scss/navigation.scss
src/assets/scss/my-css1.scss
src/assets/scss/my-css2.scss
to
-->dist/assets/css/my-css-min.css

################################################
- is it possible to use php files as well (contact.php)?

e.g.
src/pages/contact/index.php
to
--> dist/contact/index.php

################################################
- is it possible to compile all JavaScript files as one file in "my-js-min.js"?

e.g.
src/assets/js/modules/lazyload.js
src/assets/js/modules/navigation.js
src/assets/js/modules/validation.js
to 
--> dist/assets/js/my-js-min.js

################################################
- how do i use src/components/image.html and lazyload? Do you have an example?

################################################
- can I minimize all HTML and PHP files in production mode?

Thank you very much.

**Comment by roybarber** [comment]
Hi @frankdema ill answer each question below:

### Q. is it possible to include scss?

We use tailwind here in this starter template, you could add additional includes using postcss-import or [https://github.com/trysound/postcss-easy-import](https://github.com/trysound/postcss-easy-import)

### Q. is it possible to use php files as well (contact.php)?

No since this is a static site generator, php requires a server. You can however hook this upto netlify functions or other serverless services.

### Q. is it possible to compile all JavaScript files as one file in "my-js-min.js"?

This is already done, it compiles to /dist/assets/js/main.js take a look at the gulpfile and webpack config. 

### Q. how do i use src/components/image.html and lazyload? Do you have an example?

{{> image lazyload=true srcset=false src="img/imageurl/image.jpg" alt="image alt if needed"}}

### Q. can I minimize all HTML and PHP files in production mode?

php you cant use here, but if you want to minimise html on build then you could switch out beautify for a minifier here: [https://github.com/roybarber/static-starter/blob/develop/gulpfile.js#L247](https://github.com/roybarber/static-starter/blob/develop/gulpfile.js#L247) we like to tidy up the html on build and indent, rather than completely minify it

**Comment by frankdema** [comment]
Thank you very much.
